name: Build and Publish Image

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use secrets as environment variables
        env:
          VAR1: ${{ secrets.VAR1 }}
          VAR2: ${{ secrets.VAR2 }}
        run: echo "The value of VAR1 is $VAR1 and VAR2 is $VAR2"
